### ISSUE TITLE
Does string.new_wtf16 use LE or BE encoding?

### ISSUE THREAD

**Issue by eqrion** [WebAssembly/stringref#15]
What encoding scheme is used for string.new_wtf16?

The WTF-8 document mentions UTF-16 as referring to the 'encoding form' not 'encoding scheme' [1], which would define LE vs. BE. I read through the overview and saw no mention of endianness, so I'm not sure if this is something that's missing from the overview or if UTF-16 has an implied endianness from some other Unicode specification.

[1] https://simonsapin.github.io/wtf-8/#utf-16

**Comment by wingo** [comment]
Excellent question!  I think that given https://webassembly.github.io/spec/core/exec/numerics.html#aux-bytes, we should specify that the code units are stored in little-endian order (UTF-16LE encoding scheme).
