### ISSUE TITLE
Does the interpreter support `stringref` yet?

### ISSUE THREAD

**Issue by yviansu** [WebAssembly/stringref#52]
I have written a wast file according to the stringref spec. 
```
(module
    (memory 10 10)
    (type $stringref_=>_none (func (param stringref)))
    (func $string.concat (param $a stringref)
        (drop
            (local.set $a 
                (string.concat
                    (local.get $a)
                    (string.const "foo")
                )
            )
        )
    )
)
```
However, when I run the wast file through the interpreter provided in the repo, it throws an error `../tests/stringref.wast:5.41-5.50: syntax error: unknown operator stringref`, it seems that this interpreter does not support `stringref`.

Is there any other interpreter which support `stringref`?

**Comment by jakobkummerow** [comment]
Binaryen supports stringref (with `--enable-strings`); you can use that to convert .wast text to .wasm binary.
V8 supports stringref (with `--experimental-wasm-stringref`); you can use that to execute .wasm binaries.

AFAIK the reference interpreter has not been updated yet.

**Comment by yviansu** [comment]
Got it! 
Thanks for your reply!
